language: java
jdk:
  - openjdk8

#Travis CI를 어느 브랜치가 푸시될 떄 수행할지 지정.
branches:
  only:
    - master # master 브랜치에 푸시될 때만 수행.


# Travis CI 서버의 Home
cache: # 같은 의존성을 다음 배포 때 부터 받지 않도록 함.
  directories:
    - '$HOME/ .m2/repository'
    - '#HOME/ .gradle'

# master branch에 푸시 되었을 때 수행하는 명령어. clean & build 수행
script: "./gradle clean build"

# CI 실행 완료 시 메일로 자동 알람
notifications:
  email:
    recipients:
      - first11@konkuk.ac.kr